# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "develop", "main", "master" ]
  pull_request:
    branches: [ "develop", "main", "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install pytest
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_dev.txt
    - name: Test with pytest
      run: |
        python -m pytest
    - name: Test to build
      run: |
        python setup.py install
    - name: Test to build docs
      run: |
        cd docs && make html
    - name: Test to run package
      run: |
        mkdir test_tmp && cd test_tmp && python -c "import flopt"
